version: "3.1"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.frontend
    ports:
      - "5173:5173"
    volumes:
      - .:/app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.dev
    # user: "${UID}:${GID}"
    ports:
      - "8082:8082"
    env_file:
      - .env
    environment:
      DB_HOST: mariadb
      DB_PORT: 3308
    volumes:
      - ./backend:/app
      - cargo-target:/app/target
      - cargo-registry:/usr/local/cargo/registry

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "3308:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "3307:3307"

volumes:
  cargo-target:
  cargo-registry:
  mariadb_data:
