version: "3.1"

services:
  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile.frontend
    ports:
      - 5173:5173
    volumes:
      - .:/app

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend.dev
    ports:
      - 8082:8082
    volumes:
      - ./backend:/app
      - cargo-target:/app/target
      - cargo-registry:/usr/local/cargo/registry

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongodb:27017

volumes:
  cargo-target:
  cargo-registry:
